---
# tasks file for ansible-role-users
- name: install zsh
  apt: name=zsh state=present
  when: ansible_os_family == 'Debian'

- name: install zsh
  yum: name=zsh state=present
  when: ansible_os_family == 'RedHat'

- name: create users
  user: name="{{ item.key }}" comment="{{ item.value.name }}" shell="{{ item.value.shell }}" state=present
  with_dict: "{{ users_users }}"

- name: generate ssh keys
  command: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  args:
    creates: ~/.ssh/id_rsa
  with_dict: "{{ users_users }}"
  when: "{{ item.value.generate_ssh_key }}"
  become: true
  become_user: "{{ item.key }}"

- name: fetch generated public keys (you might need this to allow deploy)
  fetch: src=~/.ssh/id_rsa.pub dest="keys/{{ inventory_hostname }}-{{ item.key }}.pubkey" flat=yes
  with_dict: "{{ users_users }}"
  when: "{{ item.value.generate_ssh_key }}"
  become: true

- name: add authorized ssh public keys
  authorized_key: user="{{ item.key }}" key="{{ item.value.authorized_key }}"
  with_dict: "{{ users_users }}"

- name: setup sudoers
  template: src=etc/sudoers.d/ansible.j2 dest=/etc/sudoers.d/ansible owner=root group=root mode=0440

- name: disable user passwords
  user: name="{{ item.key }}" password=*
  with_dict: "{{ users_users|default({}) }}"
  when: "{{ item.value.disable_password }}"

- name: disable root password
  user: name=root password=*
  when: users_root_disable_password
